"""agrega_columna_activo

Revision ID: 1b5890c45e93
Revises: 7a35dbe61054
Create Date: 2026-08-07 09:27:01.136121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5890c45e93'
down_revision: Union[str, Sequence[str], None] = '7a35dbe61054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnos', sa.Column('activo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumnos', 'activo')
    # ### end Alembic commands ###
