"""crear_tabla_comprobantes

Revision ID: 4b64c60b105a
Revises: 1eb65214a810
Create Date: 2026-08-07 15:55:03.122009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b64c60b105a'
down_revision: Union[str, Sequence[str], None] = '1eb65214a810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comprobantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('profesor_id', sa.Integer(), nullable=True),
    sa.Column('numero_comprobante', sa.String(length=50), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_comprobante')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comprobantes')
    # ### end Alembic commands ###
