"""Agrega gasto_padre_id a gastos

Revision ID: 7a35dbe61054
Revises: 9702b01ea0a9
Create Date: 2026-08-05 11:32:19.841095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a35dbe61054'
down_revision: Union[str, Sequence[str], None] = '9702b01ea0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos', sa.Column('gasto_padre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gastos', 'gastos', ['gasto_padre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gastos', type_='foreignkey')
    op.drop_column('gastos', 'gasto_padre_id')
    # ### end Alembic commands ###
